### PR TITLE
Async! Modular! Typed!

### PR DESCRIPTION
**Pull request by ntninja**
… and pretty much everything got rewritten, although the basic framework remains the same.

Sorry for this really big PR, I just carried away fixing things. :wink:

The commits were edited to make per-commit review as easy as possible, so you can review them one-by-one or in batches without being irritated by the occasional huge “I moved everything someplace else” commit.

**Some caveats**:

  * `.query()` is probably broken and I did not invest any time in figuring out how it should work now (the relevant test is commented out for now)
  * `datastore.filesystem` is not ported yet
  * `datastore.serialize` backends are not streaming/async yet
  * I haven't looked at the codestyle checks in quite a while
  * I used tabs
  * For some reason the test's runtime is increased with n² over the number of elements added to the dict!? :thinking:

### CODE REVIEW

**Review by seeni-dev — APPROVED** [review]

**Review by seeni-dev — APPROVED** [review]

**Review by seeni-dev — APPROVED** [review]

**Review by seeni-dev — APPROVED** [review]

**Comment by Swixx** [comment]
@alexander255 Hey I'd like to go in and fix some of the checks that are failing. I forked off of this branch (`alexander255:master`) and want to do some testing. I'm getting a 
```
import datastore
E   ModuleNotFoundError: No module named 'datastore'
```
when running `pytest` locally. What's the best way to install the package into my local environment without a `setup.py`?

**Comment by ntninja** [comment]
For future reference: The command to run the tests is `tox -e py3X` (where X is your Python interpreter subversion)

**Comment by seeni-dev** [comment]
@alexander255 can you fix this 
Screenshot 2019-12-26 at 6 54 16 PM

**Comment by seeni-dev** [comment]
It will occur when you test filesystem or if you run tox with `datastore/filesystem/` enabled in tox's addopts

**Comment by adamjsawicki** [comment]
@alexander255 I see you made the decision to go `tabs` > `spaces`. That's giving some problems even with the `use-flake8-tabs = true` when it comes to fixing some of the styling components. Per the discussion on #6, it seemed as though @Seenivasanseeni made the decision to go spaces.

I'd like to submit a PR to @alexander255's fork with changes that make the travis build pass but want to make sure I'm not going down a rabbit hole for no reason. What is the decision?

My own two cents: I personally vote for spaces not only because of PEP8, but because tools like `black` + `autopep8` can fix a ton of styling woes and will give you spaces, as that is the standard.

**Comment by ntninja** [comment]
@Seenivasanseeni: Filesystem is still broken (see opening post), that's way it is excluded from the tests.

**Comment by seeni-dev** [comment]
@alexander255  Okay. then lets merge the changes.

**Comment by ntninja** [comment]
@Swixx: Thank you for trying to help out here! It's OK if you cannot fix all the issues, any help will be appreciated! (The decision made with this PR stands as I'm a somewhat selfish person after all – sorry everybody! :wink:)

**Comment by adamjsawicki** [comment]
@alexander255 No problem. I'll open a PR soon.

**Pull request merged**
