### PR TITLE
Move tests to external folder

### PR DESCRIPTION
**Pull request by adamjsawicki**
In reference to discussion by @alexander255 and @AliabbasMerchant discussion in #13.

### CODE REVIEW

**Comment by ntninja** [comment]
According to https://travis-ci.com/ipfs/py-datastore/jobs/282695128#L228-L231 this will not run filesystem tests anymore. Could you look into that?

**Comment by ntninja** [comment]
@Swixx: Would it be OK for you if I started on exposing that IPFS API on py-IPFS? I know I promised you that one, but I feel like doing some groundwork work right now. Waiting for your reply.

**Comment by adamjsawicki** [comment]
@alexander255 Go ahead and work on it! And I'll make the fix tomorrow.

**Review by ntninja — APPROVED** [review]
Thank you!

**Comment by ntninja** [comment]
On second thought: Why did we drop the `pytest` section in `tox.ini`? Was there nothing important in there?

**Comment by adamjsawicki** [comment]
No. It had the following:
```
[pytest]
python_files =
	test_*.py
addopts =
;	--doctest-modules
	datastore/core/test/
	datastore/filesystem/
```

Since we nest everything under `tests` they will be picked up automagically.

**Pull request merged**
